### ISSUE TITLE
GazeboのモデルをEusから動かす際のエラー

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#161]
gazeboを使ってシミュレーションしようとしたのですが、（roseusのシミュレータが大量に立ち上がってしまうので）, 
`rosrun baxter_examples joint_velocity_wobbler.py`
だと問題なく動くのですが、
eusからだと送る角度がおかしいと言われてjoint_trajectory_action_server.pyがエラーをはきます。
何が問題でしょうか？

```
$ rosrun baxter_interface joint_trajectory_action_server.py
Initializing node...
Initializing joint trajectory action server...
Running. Ctrl-c to quit
[INFO] [WallTime: 1426108056.865800] [119.942000] /rsdk_position_w_id_joint_trajectory_action_server: Executing requested joint trajectory
[ERROR] [WallTime: 1426108056.867749] [119.943000] Exception in your execute callback: negative dimensions are not allowed
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 299, in executeLoop
    self.execute_callback(goal)
  File "/home/wkentaro/semi/src/baxter_interface/src/joint_trajectory_action/joint_trajectory_action.py", line 371, in _on_trajectory_action
    dimensions_dict)
  File "/home/wkentaro/semi/src/baxter_interface/src/joint_trajectory_action/joint_trajectory_action.py", line 325, in _compute_bezier_coeff
    d_pts = bezier.de_boor_control_pts(traj_array)
  File "/home/wkentaro/semi/src/baxter_interface/src/joint_trajectory_action/bezier.py", line 138, in de_boor_control_pts
    x = np.zeros((N-1, 1))
ValueError: negative dimensions are not allowed
```

**Comment by wkentaro** [comment]
eusでは
```
[ WARN] [1426108634.889980824]: /use_sim_time is TRUE, check if /clock is pusblished or not
```
と言われています。

**Comment by aginika** [comment]
それがver1.1.0におけるbaxterのaction serverの問題です。

**Comment by aginika** [comment]
ただ今は、ver1.1.0だと軌跡が異様な形(いわゆるブレル問題)になるので、
ver1.0.0を使うように変更しています。

**Comment by wkentaro** [comment]
ありがとうございます。
3つ以上送ると上手くいきました。

2015年3月12日木曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> ただ今は、ver1.1.0だと軌跡が異様な形(いわゆるブレル問題)になるので、
> ver1.0.0を使うように変更しています。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/161#issuecomment-78472230>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>
