### ISSUE TITLE
Challenge.launch comes to error because lack of bof_data/bof.pkl.gz

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#250]
```
roslaunch jsk_2014_picking_challenge challenge.launch
```

below is the error.

```
 Traceback (most recent call last):
  File "/home/baxter/semi/src/2014-semi/jsk_2014_picking_challenge/scripts/bof_object_matcher.py", line 98, in <module>
    main()
  File "/home/baxter/semi/src/2014-semi/jsk_2014_picking_challenge/scripts/bof_object_matcher.py", line 93, in main
    matcher = BofObjectMatcher()
  File "/home/baxter/semi/src/2014-semi/jsk_2014_picking_challenge/scripts/bof_object_matcher.py", line 27, in __init__
    self._init_bof()
  File "/home/baxter/semi/src/2014-semi/jsk_2014_picking_challenge/scripts/bof_object_matcher.py", line 34, in _init_bof
    self.bof = BagOfFeatures(bof_path=bof_path)
  File "/home/baxter/semi/src/2014-semi/jsk_2014_picking_challenge/scripts/bag_of_features.py", line 16, in __init__
    self.load_bof(bof_path)
  File "/home/baxter/semi/src/2014-semi/jsk_2014_picking_challenge/scripts/bag_of_features.py", line 52, in load_bof
    with gzip.open(path, 'rb') as f:
  File "/usr/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/home/baxter/semi/src/2014-semi/jsk_2014_picking_challenge/scripts/../data/bof_data/bof.pkl.gz'
roseus_c_util [bof_object_matcher-13] process has died [pid 25455, exit code 1, cmd /home/baxter/semi/src/2014-semi/jsk_2014_picking_challenge/scripts/bof_object_matcher.py __name:=bof_object_matcher __log:=/home/baxter/.ros/log/dc0231f4-eb47-11e4-be87-b8ca3ab5d80e/bof_object_matcher-13.log].
log file: /home/baxter/.ros/log/dc0231f4-eb47-11e4-be87-b8ca3ab5d80e/bof_object_matcher-13*.log

```

**Comment by wkentaro** [comment]
I will place that data in `mouro` tomorrow.

**Comment by wkentaro** [comment]
I put it.
https://github.com/start-jsk/2014-semi/tree/master/jsk_2014_picking_challenge/data/bof_data
