### ISSUE TITLE
Baxterのroscoreがおかしいときがある?

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#396]
Baxterのroscoreがおかしいと思われるときが時たま起こります。
症状は、お互いのnodeが見つからなくなることなどのようで、
- Kinect2がrespawnを繰り返す.
- joint_trajectory_action_serverを立ち上げているのに繋がらなくなる。

対策はrebootです。

**Comment by aginika** [comment]
```
/opt/hlr/rethink-rsdk/log/hlr/
```
のlogを次なったら見てみる。

**Comment by aginika** [comment]
```
[rosmaster.threadpool][ERROR] 2015-05-05 06:20:40,252: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/site-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/indigo/lib/python2.7/site-packages/rosmaster/master_api.py", line 208, in publisher_update_task
    xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib64/python2.7/httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 844, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 806, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 787, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 113] No route to host
```
と
```
rosmaster.threadpool][ERROR] 2015-05-05 06:20:40,252: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/site-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/indigo/lib/python2.7/site-packages/rosmaster/master_api.py", line 208, in publisher_update_task
    xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)
  File "/usr/lib64/python2.7/httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 844, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 806, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 787, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 113] No route to host
```

が大量にログに出ています。

mouroをrebootしたらこのようになりました。
reboot前にnodeletが大量に死んでいることが原因の一つでしょうか？

**Comment by k-okada** [comment]
体内から外へのpingと
体外mouroから体内へのping
をずっと続けて置いてみてください


Baxterはdhcpだっけ、この前トラブった時にスタテックしたっけ？
なんとなくだけど情報理工のdhcpがrenewするタイミングとかの設定をミスっているか、なんか理解していないんじゃないかな、と思っています。

スタテックにすれば大丈夫なきがしていますが。

--
◉ Kei Okada

2015/05/05 19:25、Yuto Inagaki <notifications@github.com> のメッセージ:

**Comment by aginika** [comment]
了解です。dhcpかどうか確認してみます。

次回なったらping行います。

**Comment by garaemon** [comment]
これはCLOSE_WAIT問題ではなさそうですね

**Comment by garaemon** [comment]
同じ時刻のsyslogも見てみると良いと思います

**Comment by k-okada** [comment]
タブん一瞬切れているんじゃないかというきがする

--
◉ Kei Okada

2015/05/05 20:01、Yuto Inagaki <notifications@github.com> のメッセージ:

**Comment by k-okada** [comment]
なので切れてからでは無くて切れた時にどうかを知りたい
そういう意味ではpingではなくsyslogでよさそう

--
◉ Kei Okada

2015/05/05 20:14、Kei Okada <kei.okada@gmail.com> のメッセージ:

**Comment by garaemon** [comment]
dhcpならsyslogにDHCP REQUESTとかなんとか出力があるはずですね

**Comment by aginika** [comment]
なるほど、syslogを後で見てみようと思いまsう。

**Comment by aginika** [comment]
今日もなりました。
@k-okada 先ほどの状態はこのスレッドの症状です。

**Comment by k-okada** [comment]
次こそsyslog　を見るのを忘れないようにしましょう．

**Comment by wkentaro** [comment]
ftp://baxter.jsk.imi.i.u-tokyo.ac.jp/sys-log/syslog.log

**Comment by aginika** [comment]
問題になったらまた開きます。
